// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6E0KawmJi5WGtHagNMluz8dnsq9MRGTg',
    appId: '1:349601621134:web:411f654323a2fc8f8995df',
    messagingSenderId: '349601621134',
    projectId: 'travelly-90e1c',
    authDomain: 'travelly-90e1c.firebaseapp.com',
    storageBucket: 'travelly-90e1c.appspot.com',
    measurementId: 'G-H3WDVVJG73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3xVyUye9dVYwLYptD69ha_lrvNhQ1aqA',
    appId: '1:349601621134:android:d25e1fd42f853f9d8995df',
    messagingSenderId: '349601621134',
    projectId: 'travelly-90e1c',
    storageBucket: 'travelly-90e1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9iz7mIFFxWVgtOdDOb5cFsSHY8C9IvOc',
    appId: '1:349601621134:ios:64f8791839fa05488995df',
    messagingSenderId: '349601621134',
    projectId: 'travelly-90e1c',
    storageBucket: 'travelly-90e1c.appspot.com',
    iosClientId: '349601621134-qh87jicck1a96bjlv476tlup169u9hvm.apps.googleusercontent.com',
    iosBundleId: 'com.f46.demo.f46',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9iz7mIFFxWVgtOdDOb5cFsSHY8C9IvOc',
    appId: '1:349601621134:ios:64f8791839fa05488995df',
    messagingSenderId: '349601621134',
    projectId: 'travelly-90e1c',
    storageBucket: 'travelly-90e1c.appspot.com',
    iosClientId: '349601621134-qh87jicck1a96bjlv476tlup169u9hvm.apps.googleusercontent.com',
    iosBundleId: 'com.f46.demo.f46',
  );
}
